# Generated by Django 4.2.2 on 2023-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0008_remove_ship_params_carrier_alter_t1_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_params',
            name='weight',
        ),
        migrations.AddField(
            model_name='ship_params',
            name='breadth',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='height',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='length',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='ship_params',
            name='time',
            field=models.FloatField(default=1),
        ),
    ]
