# Generated by Django 4.2.2 on 2023-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0011_remove_ship_params_time_remove_ship_params_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_zip', models.IntegerField(blank=True, db_column='Dest_ZIP', null=True)),
                ('mode', models.IntegerField(blank=True, db_column='Mode', null=True)),
                ('zone', models.IntegerField(blank=True, db_column='Zone', null=True)),
            ],
            options={
                'db_table': 'zonetable',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='ship_params',
            name='lat1',
        ),
        migrations.RemoveField(
            model_name='ship_params',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='ship_params',
            name='lon1',
        ),
        migrations.RemoveField(
            model_name='ship_params',
            name='lon2',
        ),
        migrations.AddField(
            model_name='ship_params',
            name='actual_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='dest_zip',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='src_zip',
            field=models.IntegerField(default=10001),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='unit_dim',
            field=models.CharField(choices=[('m', 'meters'), ('cm', 'centimeters'), ('in', 'inches'), ('ft', 'feet')], default='in', max_length=2),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='unit_wt',
            field=models.CharField(choices=[('kg', 'kilograms'), ('g', 'grams'), ('lb', 'pounds')], default='lb', max_length=2),
        ),
    ]
