# Generated by Django 4.2.2 on 2023-07-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0013_remove_ship_params_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_params',
            name='slot',
        ),
    ]
