# Generated by Django 4.2.2 on 2023-07-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0014_remove_ship_params_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship_params',
            old_name='unit_dim',
            new_name='unit_bre',
        ),
        migrations.AddField(
            model_name='ship_params',
            name='unit_hei',
            field=models.CharField(choices=[('m', 'meters'), ('cm', 'centimeters'), ('in', 'inches'), ('ft', 'feet')], default='in', max_length=2),
        ),
        migrations.AddField(
            model_name='ship_params',
            name='unit_len',
            field=models.CharField(choices=[('m', 'meters'), ('cm', 'centimeters'), ('in', 'inches'), ('ft', 'feet')], default='in', max_length=2),
        ),
    ]
