# Generated by Django 4.2.2 on 2023-06-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0005_alter_t1_price_alter_t1_time_alter_t1_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t1',
            options={'managed': False},
        ),
    ]
