# Generated by Django 4.2.2 on 2023-06-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0006_alter_t1_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t1',
            table='t1',
        ),
    ]
