# Generated by Django 4.2.2 on 2023-06-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0007_alter_t1_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_params',
            name='carrier',
        ),
        migrations.AlterModelTable(
            name='t1',
            table='air',
        ),
    ]
