# Generated by Django 4.2.2 on 2023-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipparams', '0009_remove_ship_params_weight_ship_params_breadth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_params',
            name='time',
            field=models.FloatField(default=2),
        ),
    ]
